[mgr]
ratio           = [ 1, 3, 3 ]

[preview]
tab_size        = 2
max_width       = 1200
max_height      = 1600

[plugin]
prepend_previewers = [
    { mime = "text/csv", run = "miller_csv"},
    { name = "*.md", run = "glow" }
]
append_previewers = [
    { mime = "*", run = "hexyl"},
]
