[manager]
ratio           = [ 1, 3, 3 ]

[preview]
tab_size        = 2
max_width       = 1200
max_height      = 1600

[plugin]
prepend_previewers = [
    { mime = "text/csv", exec = "miller_csv"},
    { name = "*.md", exec = "glow" }
]
append_previewers = [
    { mime = "*", exec = "hexyl"},
]
