matches:
  - trigger: ";date"
    replace: "{{d}}"
    vars:
      - name: d
        type: date
        params:
          format: "%Y-%m-%d"
  - trigger: ";ts"
    replace: "{{mydate}}"
    vars:
      - name: mydate
        type: date
        params:
          format: "%Y-%m-%dT%H%M%S"
  - trigger: ";_date"
    replace: "{{mydate}}"
    vars:
      - name: mydate
        type: date
        params:
          format: "%Y_%m_%d"
  - trigger: ";pts"
    replace: 'datetime.datetime.now().strftime("%Y_%m_%dT%H%M%S")'
  - trigger: ";ip"
    replace: "{{output}}"
    vars:
      - name: output
        type: shell
        params:
          cmd: "curl ifconfig.so"
  - trigger: ";pb"
    replace: '<div style="page-break-after: always;"></div>'
